### ISSUE TITLE
wis2box-create-config bad bounding box

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2box#540]
The wis2box-create-config creates a bad bounding box when the defaults are accepted, with double brackets used, e.g. [[ ... ]].

```
    extents:
        spatial:
            - bbox: [[-180, -90, 180, 90]]
              crs: 4326
```
