### ISSUE TITLE
Unknown file type (bufr4) : data-mappings should not be driven by file-extension

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#619]
wis2box prints error when no data-mappings.yml configured for data produced in the public bucket if the file extension changed

for example:

```
data:
    it-maaike-test2.data.core.weather.surface-based-observations.temp:
        plugins:
            BU:
                - plugin: wis2box.data.bufr4.ObservationDataBUFR
                  notify: true
                  buckets:
                    - ${WIS2BOX_STORAGE_INCOMING}
                  file-pattern: '^.*\.BU$'
```

results in:
`{/app/wis2box/pubsub/subscribe.py:56} ERROR - handle() error: Topic Hierarchy validation error: Unknown file type (bufr4) for topic it-maaike-test2.data.core.weather.surface-based-observations.temp. Did not match any of the following:BU, b, bin, bufr`
![image](https://github.com/wmo-im/wis2box/assets/19169339/aa7b7e03-be0b-4015-809e-26813432cced)

when ingesting a .BU file, even though the file is correctly published

I believe the data-mappings should not be driven by file-extension at the first level, perhaps the first-level should be the bucket in which the file lands .
@tomkralidis can we consider changing the way plugins are associated to datasets ?

**Comment by maaikelimper** [comment]
The current workaround is to add an entry for bufr4 (which will not be used as the bufr4 file is produced in incoming not public:
data:
```
    it-maaike-test2.data.core.weather.surface-based-observations.temp:
        plugins:
            BU:
                - plugin: wis2box.data.bufr4.ObservationDataBUFR
                  notify: true
                  buckets:
                    - ${WIS2BOX_STORAGE_INCOMING}
                  file-pattern: '^.*\.BU$'
            bufr4:
                - plugin: wis2box.data.bufr4.ObservationDataBUFR
                  notify: true
                  buckets:
                    - ${WIS2BOX_STORAGE_INCOMING}
                  file-pattern: '^.*\.bufr4$'
```
