### ISSUE TITLE
add templates for publishing non synop/temp data

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#624]
I have received multiple requests regardging publishing non synop/temp data :

we could address some of these issues by:
- adding additional metadata-templates
- update documentation referring the wis2-topic-hierarchy and wcmp2 repositories
- update documentation with more examples for data-types other than synop/temp (using universal pipeline)

We could also add more templates like currently we have:
```
{
    "title": "Hourly synoptic observations from fixed-land stations (SYNOP) ($CENTRE_ID)",
    "identifier": "urn:x-wmo:md:$CENTRE_ID:surface-based-observations.synop",
    "topicHierarchy": "$CENTRE_ID.data.$DATA_POLICY.weather.surface-based-observations.synop",
    "language": "en",
    "retention": "P30D",
    "resolution": "P1H",
    "keywords": ["surface", "land", "observations"],
    "duplicateFromContact": true
}
```
and
```
{
    "title": "Upper-level temperature/humidity/wind reports from fixed-land stations (TEMP) ($CENTRE_ID)",
    "identifier": "urn:x-wmo:md:$CENTRE_ID:surface-based-observations.temp",
    "topicHierarchy": "$CENTRE_ID.data.$DATA_POLICY.weather.surface-based-observations.temp",
    "language": "en",
    "retention": "P30D",
    "resolution": "P12H",
    "keywords": ["upper air", "humidity", "wind", "observations"],
    "duplicateFromContact": true
}
```

**Comment by tomkralidis** [comment]
2024-02-06:
- we need to consider support data types on a case-by-case basis to ensure alignment in WIS2 proper
- core data has a defined set per the Unified Data Policy/core catalogue appendix
- as WTH evolves, we can turn back on topic validation via pywis-topics
- see 'Variety of data pipelines' in https://github.com/wmo-im/wis2box/wiki/ProjectRoadmap-1.0

**Comment by david-i-berry** [comment]
Something like this for drifters (using the MCF format);

```yaml
mcf:
    version: 1.0

metadata:
    identifier: urn:wmo:md:${WIS2CENTRE}:surface-observations:drifting-buoy
    hierarchylevel: dataset

identification:
    title: Surface observations from the ${COUNTRY} drifting buoy program
    abstract:
        Surface observations (sea surface temperature, sea level pressure, waves, current) from the \
        ${COUNTRY} drifting buoy program.
    dates:
        creation: null
    keywords:
        default:
            keywords:
                - observations
                - drifting buoy
                - ocean
                - marine
                - waves
                - sea surface temperature
                - sea level pressure
                - ocean currents
        wmo:
            keywords:
                - weather
                - ocean
                - climate
            keywords_type: theme
            vocabulary:
                name: Earth system disciplines as defined by the WMO Unified Data Policy, Resolution 1 (Cg-Ext(2021), Annex 1.
                url: https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/earth-system-discipline/index.csv
    extents:
        spatial:
            - bbox: [-180.0, -90.0, 180.0, 90.0]
              crs: 4326
        temporal:
            - begin: null
              end: null
              resolution: P1H
    rights: WMO Unified Policy for the International Exchange of Earth System Data
    url: https://example.org/fixme

contact:
    pointOfContact: &contact_poc
        organization: ${ORGANISATION}
        url: ${ORGANISATION_HOMEPAGE}
        individualname: ${METADATA_CONTACT_INDIVIDUAL_NAME}
        positionname: ${METADATA_CONTACT_POSITION_NAME}
        phone: ${METADATA_CONTACT_PHONE}
        fax: ${METADATA_CONTACT_FAX}
        address: ${METADATA_CONTACT_ADDRESS}
        city: ${METADATA_CONTACT_CITY}
        administrativearea: ${METADATA_CONTACT_ADMINISTRATIVE_AREA}
        postalcode: ${METADATA_CONTACT_POSTAL_CODE}
        country: ${METADATA_CONTACT_COUNTRY}
        email: ${METADATA_CONTACT_POSITION_EMAIL}
        hoursofservice: ${HOURS_OF_SERVICE}
        contactinstructions: ${METADATA_CONTACT_INSTRUCTION}

    distributor: *contact_poc

```

Where do we want to collect the templates?
